version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run: 
          command: |
            make test-cover
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
